services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=employees
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - db
      - mongo
    networks:
      - sem-net
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employees
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sem-net
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sem-net
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - sem-net
networks:
  sem-net:
    driver: bridge
volumes:
  mysql-data:
  mongo-data:
